### ISSUE TITLE
빌드는 어떻게 하나요?

### ISSUE THREAD

**Issue by xenon245** [Luxusio/ADOFAI-Map-Converter#4]
이 프로그램을 intellij로 빌드하려고 하는데 gradlew jar 명령어를 사용하였지만 빌드에서 버그가 생겨 zip파일이 빌드가 되지 않네요. 어떻게 해야하나요?

**Comment by Luxusio** [comment]
빌드 메세지가 어떻게 되나요? 저는 OpenJDK 11을 쓰는데 문제없이 잘 됩니다

**Comment by xenon245** [comment]
제가 16을 써서 그런가? 11로 바꿔보고 안되면 다시 글 올리겠습니다

**Comment by xenon245** [comment]
zip파일의 생성위치를 알 수 있을 까요?

**Comment by xenon245** [comment]
openjdk11로 바꾸고 나니 빌드 오류메시지는 안뜨는데 파일이 생성 안 된 듯요
